# Note that only one of these targets is required

ticketmaster_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: sandbox-450016
      dataset: ticketmaster_dataset_n
      threads: 4
      OPTIONAL_CONFIG: VALUE
